// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package microdemo

import (
	"context"
	"fmt"
)

type ProfileRequest struct {
	UserId   int64   `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Scenario *string `thrift:"scenario,2,optional" frugal:"2,optional,string" json:"scenario,omitempty"`
}

func NewProfileRequest() *ProfileRequest {
	return &ProfileRequest{}
}

func (p *ProfileRequest) InitDefault() {
}

func (p *ProfileRequest) GetUserId() (v int64) {
	return p.UserId
}

var ProfileRequest_Scenario_DEFAULT string

func (p *ProfileRequest) GetScenario() (v string) {
	if !p.IsSetScenario() {
		return ProfileRequest_Scenario_DEFAULT
	}
	return *p.Scenario
}
func (p *ProfileRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ProfileRequest) SetScenario(val *string) {
	p.Scenario = val
}

func (p *ProfileRequest) IsSetScenario() bool {
	return p.Scenario != nil
}

func (p *ProfileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileRequest(%+v)", *p)
}

var fieldIDToName_ProfileRequest = map[int16]string{
	1: "userId",
	2: "scenario",
}

type ProfileResponse struct {
	UserId int64  `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Name   string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	City   string `thrift:"city,3,required" frugal:"3,required,string" json:"city"`
	Bio    string `thrift:"bio,4,required" frugal:"4,required,string" json:"bio"`
}

func NewProfileResponse() *ProfileResponse {
	return &ProfileResponse{}
}

func (p *ProfileResponse) InitDefault() {
}

func (p *ProfileResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *ProfileResponse) GetName() (v string) {
	return p.Name
}

func (p *ProfileResponse) GetCity() (v string) {
	return p.City
}

func (p *ProfileResponse) GetBio() (v string) {
	return p.Bio
}
func (p *ProfileResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *ProfileResponse) SetName(val string) {
	p.Name = val
}
func (p *ProfileResponse) SetCity(val string) {
	p.City = val
}
func (p *ProfileResponse) SetBio(val string) {
	p.Bio = val
}

func (p *ProfileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileResponse(%+v)", *p)
}

var fieldIDToName_ProfileResponse = map[int16]string{
	1: "userId",
	2: "name",
	3: "city",
	4: "bio",
}

type RecommendRequest struct {
	UserId   int64   `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Limit    int32   `thrift:"limit,2,optional" frugal:"2,optional,i32" json:"limit,omitempty"`
	Scenario *string `thrift:"scenario,3,optional" frugal:"3,optional,string" json:"scenario,omitempty"`
}

func NewRecommendRequest() *RecommendRequest {
	return &RecommendRequest{
		Limit: 3,
	}
}

func (p *RecommendRequest) InitDefault() {
	p.Limit = 3
}

func (p *RecommendRequest) GetUserId() (v int64) {
	return p.UserId
}

var RecommendRequest_Limit_DEFAULT int32 = 3

func (p *RecommendRequest) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return RecommendRequest_Limit_DEFAULT
	}
	return p.Limit
}

var RecommendRequest_Scenario_DEFAULT string

func (p *RecommendRequest) GetScenario() (v string) {
	if !p.IsSetScenario() {
		return RecommendRequest_Scenario_DEFAULT
	}
	return *p.Scenario
}
func (p *RecommendRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *RecommendRequest) SetLimit(val int32) {
	p.Limit = val
}
func (p *RecommendRequest) SetScenario(val *string) {
	p.Scenario = val
}

func (p *RecommendRequest) IsSetLimit() bool {
	return p.Limit != RecommendRequest_Limit_DEFAULT
}

func (p *RecommendRequest) IsSetScenario() bool {
	return p.Scenario != nil
}

func (p *RecommendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendRequest(%+v)", *p)
}

var fieldIDToName_RecommendRequest = map[int16]string{
	1: "userId",
	2: "limit",
	3: "scenario",
}

type RecommendItem struct {
	PostId int64  `thrift:"postId,1,required" frugal:"1,required,i64" json:"postId"`
	Title  string `thrift:"title,2,required" frugal:"2,required,string" json:"title"`
	Reason string `thrift:"reason,3,required" frugal:"3,required,string" json:"reason"`
}

func NewRecommendItem() *RecommendItem {
	return &RecommendItem{}
}

func (p *RecommendItem) InitDefault() {
}

func (p *RecommendItem) GetPostId() (v int64) {
	return p.PostId
}

func (p *RecommendItem) GetTitle() (v string) {
	return p.Title
}

func (p *RecommendItem) GetReason() (v string) {
	return p.Reason
}
func (p *RecommendItem) SetPostId(val int64) {
	p.PostId = val
}
func (p *RecommendItem) SetTitle(val string) {
	p.Title = val
}
func (p *RecommendItem) SetReason(val string) {
	p.Reason = val
}

func (p *RecommendItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendItem(%+v)", *p)
}

var fieldIDToName_RecommendItem = map[int16]string{
	1: "postId",
	2: "title",
	3: "reason",
}

type RecommendResponse struct {
	UserId int64            `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Items  []*RecommendItem `thrift:"items,2,required" frugal:"2,required,list<RecommendItem>" json:"items"`
}

func NewRecommendResponse() *RecommendResponse {
	return &RecommendResponse{}
}

func (p *RecommendResponse) InitDefault() {
}

func (p *RecommendResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *RecommendResponse) GetItems() (v []*RecommendItem) {
	return p.Items
}
func (p *RecommendResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *RecommendResponse) SetItems(val []*RecommendItem) {
	p.Items = val
}

func (p *RecommendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendResponse(%+v)", *p)
}

var fieldIDToName_RecommendResponse = map[int16]string{
	1: "userId",
	2: "items",
}

type ProfileService interface {
	GetProfile(ctx context.Context, req *ProfileRequest) (r *ProfileResponse, err error)
}

type ProfileServiceGetProfileArgs struct {
	Req *ProfileRequest `thrift:"req,1" frugal:"1,default,ProfileRequest" json:"req"`
}

func NewProfileServiceGetProfileArgs() *ProfileServiceGetProfileArgs {
	return &ProfileServiceGetProfileArgs{}
}

func (p *ProfileServiceGetProfileArgs) InitDefault() {
}

var ProfileServiceGetProfileArgs_Req_DEFAULT *ProfileRequest

func (p *ProfileServiceGetProfileArgs) GetReq() (v *ProfileRequest) {
	if !p.IsSetReq() {
		return ProfileServiceGetProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProfileServiceGetProfileArgs) SetReq(val *ProfileRequest) {
	p.Req = val
}

func (p *ProfileServiceGetProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProfileServiceGetProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceGetProfileArgs(%+v)", *p)
}

var fieldIDToName_ProfileServiceGetProfileArgs = map[int16]string{
	1: "req",
}

type ProfileServiceGetProfileResult struct {
	Success *ProfileResponse `thrift:"success,0,optional" frugal:"0,optional,ProfileResponse" json:"success,omitempty"`
}

func NewProfileServiceGetProfileResult() *ProfileServiceGetProfileResult {
	return &ProfileServiceGetProfileResult{}
}

func (p *ProfileServiceGetProfileResult) InitDefault() {
}

var ProfileServiceGetProfileResult_Success_DEFAULT *ProfileResponse

func (p *ProfileServiceGetProfileResult) GetSuccess() (v *ProfileResponse) {
	if !p.IsSetSuccess() {
		return ProfileServiceGetProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProfileServiceGetProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProfileResponse)
}

func (p *ProfileServiceGetProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProfileServiceGetProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceGetProfileResult(%+v)", *p)
}

var fieldIDToName_ProfileServiceGetProfileResult = map[int16]string{
	0: "success",
}

type RecommendService interface {
	GetRecommendations(ctx context.Context, req *RecommendRequest) (r *RecommendResponse, err error)
}

type RecommendServiceGetRecommendationsArgs struct {
	Req *RecommendRequest `thrift:"req,1" frugal:"1,default,RecommendRequest" json:"req"`
}

func NewRecommendServiceGetRecommendationsArgs() *RecommendServiceGetRecommendationsArgs {
	return &RecommendServiceGetRecommendationsArgs{}
}

func (p *RecommendServiceGetRecommendationsArgs) InitDefault() {
}

var RecommendServiceGetRecommendationsArgs_Req_DEFAULT *RecommendRequest

func (p *RecommendServiceGetRecommendationsArgs) GetReq() (v *RecommendRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetRecommendationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetRecommendationsArgs) SetReq(val *RecommendRequest) {
	p.Req = val
}

func (p *RecommendServiceGetRecommendationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetRecommendationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendationsArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendationsArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetRecommendationsResult struct {
	Success *RecommendResponse `thrift:"success,0,optional" frugal:"0,optional,RecommendResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetRecommendationsResult() *RecommendServiceGetRecommendationsResult {
	return &RecommendServiceGetRecommendationsResult{}
}

func (p *RecommendServiceGetRecommendationsResult) InitDefault() {
}

var RecommendServiceGetRecommendationsResult_Success_DEFAULT *RecommendResponse

func (p *RecommendServiceGetRecommendationsResult) GetSuccess() (v *RecommendResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetRecommendationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetRecommendationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*RecommendResponse)
}

func (p *RecommendServiceGetRecommendationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetRecommendationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendationsResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendationsResult = map[int16]string{
	0: "success",
}
