// Code generated by Kitex v0.16.1. DO NOT EDIT.

package recommendservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	microdemo "go-playground/kitex_gen/microdemo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetRecommendations(ctx context.Context, req *microdemo.RecommendRequest, callOptions ...callopt.Option) (r *microdemo.RecommendResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRecommendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRecommendServiceClient struct {
	*kClient
}

func (p *kRecommendServiceClient) GetRecommendations(ctx context.Context, req *microdemo.RecommendRequest, callOptions ...callopt.Option) (r *microdemo.RecommendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendations(ctx, req)
}
