// Code generated by Kitex v0.16.1. DO NOT EDIT.

package recommendservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	microdemo "go-playground/kitex_gen/microdemo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetRecommendations": kitex.NewMethodInfo(
		getRecommendationsHandler,
		newRecommendServiceGetRecommendationsArgs,
		newRecommendServiceGetRecommendationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	recommendServiceServiceInfo                = NewServiceInfo()
	recommendServiceServiceInfoForClient       = NewServiceInfoForClient()
	recommendServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return recommendServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RecommendService"
	handlerType := (*microdemo.RecommendService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "microdemo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getRecommendationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*microdemo.RecommendServiceGetRecommendationsArgs)
	realResult := result.(*microdemo.RecommendServiceGetRecommendationsResult)
	success, err := handler.(microdemo.RecommendService).GetRecommendations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetRecommendationsArgs() interface{} {
	return microdemo.NewRecommendServiceGetRecommendationsArgs()
}

func newRecommendServiceGetRecommendationsResult() interface{} {
	return microdemo.NewRecommendServiceGetRecommendationsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetRecommendations(ctx context.Context, req *microdemo.RecommendRequest) (r *microdemo.RecommendResponse, err error) {
	var _args microdemo.RecommendServiceGetRecommendationsArgs
	_args.Req = req
	var _result microdemo.RecommendServiceGetRecommendationsResult
	if err = p.c.Call(ctx, "GetRecommendations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
