// Code generated by Kitex v0.16.1. DO NOT EDIT.
package recommendservice

import (
	server "github.com/cloudwego/kitex/server"
	microdemo "go-playground/kitex_gen/microdemo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler microdemo.RecommendService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler microdemo.RecommendService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
