// Code generated by Kitex v0.16.1. DO NOT EDIT.

package profileservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	microdemo "go-playground/kitex_gen/microdemo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetProfile": kitex.NewMethodInfo(
		getProfileHandler,
		newProfileServiceGetProfileArgs,
		newProfileServiceGetProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	profileServiceServiceInfo                = NewServiceInfo()
	profileServiceServiceInfoForClient       = NewServiceInfoForClient()
	profileServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return profileServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return profileServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return profileServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProfileService"
	handlerType := (*microdemo.ProfileService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "microdemo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*microdemo.ProfileServiceGetProfileArgs)
	realResult := result.(*microdemo.ProfileServiceGetProfileResult)
	success, err := handler.(microdemo.ProfileService).GetProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProfileServiceGetProfileArgs() interface{} {
	return microdemo.NewProfileServiceGetProfileArgs()
}

func newProfileServiceGetProfileResult() interface{} {
	return microdemo.NewProfileServiceGetProfileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetProfile(ctx context.Context, req *microdemo.ProfileRequest) (r *microdemo.ProfileResponse, err error) {
	var _args microdemo.ProfileServiceGetProfileArgs
	_args.Req = req
	var _result microdemo.ProfileServiceGetProfileResult
	if err = p.c.Call(ctx, "GetProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
